[[generators]]
template = 'article.pug'
data = 'articles/*.md'
target = 'articles'

[[generators]]
template = 'name.pug'
data = 'names/*'
target = 'names'

[[generators]]
template = 'inspiration.pug'
data = 'inspiration/*'
target = 'inspiration'

[[generators]]
template = 'rec.pug'
data = 'recs/*'
target = 'empfehlungen'

[[generators]]
template = 'project.pug'
data = 'projects/*.yml'
target = 'projects'